### ISSUE TITLE
Add missing powerlevel10k icons

### ISSUE THREAD

**Issue by karljs** [fabrizioschiavi/pragmatapro#174]
[Powerlevel10k](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k), which is a popular `zsh` theme, tries to use at least a few characters that PragmataPro doesn't include.  When you run `p10k configure`, it tries to check what support you have by asking about a diamond character, which I do see using PragmataPro, and then a lock character, which I do not see.

**Comment by fabrizioschiavi** [comment]
I'll fix it soon. Thanks to letting me know

**Comment by yourfate** [comment]
I actually saw the lock character on my system. Though on the next screen there were some spacing issues.

**Comment by TheSecEng** [comment]
In the mean time, if you are using iTerm2 you can pick a fallback font. That allows you to us PragmataPro as the main font and then fallback to another font for non-ascii

**Comment by fabrizioschiavi** [comment]
I added all the possible _powerlevel10k_ icons since v_0.829 but I must warn you probably some icons are removed because in conflict with existing PragmataPro glyphs. The same that happens with _nerd icons_. Unfortunately icons has codepoints often used by fonts and not empty.
I submitted [this](https://github.com/ryanoasis/nerd-fonts/pull/609) pull request to _nerd fonts_ project that **IS** the solution but without success.
I can’t do more than this. Sorry.
