### ISSUE TITLE
Braille without helper lines

### ISSUE THREAD

**Issue by towolf** [fabrizioschiavi/pragmatapro#22]
Popular process viewer [`htop`](http://hisham.hm/htop/) introduced graphs using braille glyphs [to increase terminal resolution](https://www.youtube.com/watch?v=MNawjRkkTZU).

PP has helper lines for braille that do not serve a clear purpose. Side effect is that HTOP (and elsewhere) braille "dot matrix display" looks odd.

**Comment by fabrizioschiavi** [comment]
Thanks @towolf ! 
I'll fix it

**Comment by fabrizioschiavi** [comment]
Tobias, I have a doubt: 
are you sure that helper lines in Braille are useless in every software?
I wouldn’t have to go back

**Comment by towolf** [comment]
Well, most importantly the lines certainly do not help the blind. And for regular user of braille they expect the dots and nothing else I assume.

The Unicode standard does not prescribe the shapes of the dots. But the most widespread rendering is just plain dots matrix patterns.

Now, the added advantage that has been discovered is, that the braille glyphs can be used for for high resolution pixel rendering in terminals. If Pragmata is the only font that deviates from this pseudo-standard, then I would suggest to remove the helper lines.

What made you include them? Was this your idea?

**Comment by towolf** [comment]
There’s discussion here: https://en.wikipedia.org/wiki/Braille_Patterns

**Comment by fabrizioschiavi** [comment]
I've included helpers line because the space between the Braille symbols are too thin and to avoid confusion at the touch
![screen shot 2016-04-07 at 17 55 49](https://cloud.githubusercontent.com/assets/1576663/14358393/0ecb8718-fced-11e5-889b-eda8e4ea4fea.png)
![simulazione senza helpers](https://cloud.githubusercontent.com/assets/1576663/14358431/32dee03c-fced-11e5-9503-183f5911024d.png)


Also these thin lines in low size in some OSs can be disappear

![screen shot 2016-04-07 at 17 50 38](https://cloud.githubusercontent.com/assets/1576663/14358376/f4a3141e-fcec-11e5-8df5-d76f6439fcda.png)

Anyway the solution I propose is to design Braille symbols without helpers as default and to enable Braille symbols with helpers selecting an OpenType Stylistic Set.

Do you agree?

**Comment by towolf** [comment]
> Anyway the solution I propose is to design Braille symbols without helpers as default and to enable Braille symbols with helpers selecting an OpenType Stylistic Set.
>
> Do you agree?

Yes absolutely. Doing both is the perfect solution with the expected look being the default. :+1:

**Comment by towolf** [comment]
Thanks a lot, I've tried out 0.823, and to me it looks like the helper lines are still there on bold face: [Here's a quick video](https://youtu.be/-QYxyWN2Soc). The program makes the top 10% of CPU plot bold, I think.

**Comment by fabrizioschiavi** [comment]
You've right @towolf
