### ISSUE TITLE
U+3001 U+3002

### ISSUE THREAD

**Issue by CNMan** [fabrizioschiavi/pragmatapro#23]
![img1](https://i.imgur.com/bgspSnw.png)
![img1](https://i.imgur.com/TDjHMYlg.png)
![img1](https://i.imgur.com/JQi3KLG.png)
![img1](https://i.imgur.com/5TfmnbG.png)

Period should be the lower left corner instead of the center

**Comment by CNMan** [comment]
also U+3001

**Comment by fabrizioschiavi** [comment]
Thanks @CNMan I'll fix these punctuations today 😊

**Comment by railwaycat** [comment]
Actually this issue is bit more complex.

In Mainland China and Japan (Japanese and Simplified Chinese), the standard is placing U+3001 and U+3002 at lower left corner when sentences are horizontal; and at upper right corner when sentences are vertical. 

The standard in Taiwan and Hong Kong (Traditional Chinese) are different, they are placing exactly at the center, for both horizontal and vertical cases. 

So my suggestion is leave CJK symbols and characters to CJK fonts, let's don't have them in PragmataPro. CJK fonts for their languages/standards should always have correct symbols/characters.

**Comment by railwaycat** [comment]
If PragmataPro don't have U+3000 to U+3030, they will fallback to CJK fonts as settings.

**Comment by fabrizioschiavi** [comment]
Thanks @railwaycat for this very good suggestion. Probably it's the right solution

**Comment by be5invis** [comment]
@fabrizioschiavi 
To clarify, in Traditional Chinese used in Taiwan, `。` and `、` ARE centered, while in Mainland and Japan, they should be placed at left-bottom corner (horizontal layout), or top-right corner (vertical layout).

![](http://blogs.adobe.com/CCJKType/files/2015/03/tombo-example.jpg)

**Comment by fabrizioschiavi** [comment]
thanks @be5invis for your useful clarification!

**Comment by AnastasiaDunbar** [comment]
I'd still want to see monospaced Chinese (2 characters wide (or 1 if you're a madlad)).
