### ISSUE TITLE
Missing Nerd font icon

### ISSUE THREAD

**Issue by inflation** [fabrizioschiavi/pragmatapro#231]
<img width="73" alt="Screen Shot 2021-10-26 at 2 41 25 PM" src="https://user-images.githubusercontent.com/2375962/138822467-9c063f79-5a3b-4abf-8f83-54aa3b182397.png">
<img width="54" alt="Screen Shot 2021-10-26 at 2 41 35 PM" src="https://user-images.githubusercontent.com/2375962/138822479-2457a967-132a-476c-b626-6cfea7ced06f.png">

Former is the Hack font with Nerd icons.

**Comment by inflation** [comment]
Another one (Rust icon):
<img width="113" alt="CleanShot 2021-11-03 at 09 09 41@2x" src="https://user-images.githubusercontent.com/2375962/139980852-7eb27974-52d2-4e33-9ce8-7faa410bada7.png">
<img width="49" alt="Screen Shot 2021-11-03 at 9 09 30 AM" src="https://user-images.githubusercontent.com/2375962/139980917-83ed87a3-724d-4dca-a998-fb32684be69f.png">

**Comment by inflation** [comment]
Wrong icon:
<img width="118" alt="image" src="https://user-images.githubusercontent.com/2375962/140690175-d525ba84-0b7d-46e4-baea-1b01983918d6.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/2375962/140690197-5f1f49a1-ee47-44a6-96b5-67c71c7ff98f.png">

**Comment by vricop** [comment]
Missing icons. It looks like there's quite a few icons missing. I tink the missing icons are the ones from **[https://microsoft.github.io/vscode-codicons/dist/codicon.html](codicons)**, the VSCode icons, NerdFonts come with them, but if search for them in the help files (All_chars.rtf) I can't seem to find any.

Can you fix it please?

Thanks in advance great font, astonishing work, keep it up.

![image](https://user-images.githubusercontent.com/3494708/192091697-c620b710-883d-4dbf-b56e-dd43d2d85044.png)

**Comment by fabrizioschiavi** [comment]
Thanks @vricop to help me in fixing this situation!

**Comment by vricop** [comment]
> 

## More on missing NerdFont glyphs

I've been making some tests in order to figure out what's going on with the missing icons. First of all here's screenshot of DankMono, a premium font that I bought no long ago:

![DankMono Nerd Font](https://user-images.githubusercontent.com/3494708/192318427-2e3c5d45-4f8c-411b-81de-672c656fafe6.png)

### This is my vim configuration for using codeicons in DankMono*

On the left you can see all the codicons (VSCode icons) that are I'm using. This overwrites CMP default icons. On the right —the floating window— the default icons configured in CMP —an autocomplete plugin for VIM. As you can see this plugin is already using the codeicons glyphs from NerdFont, and, as you can see, it's telling us that is using either one glyph or another (`"A" | "B"`).

*DankMono: doesn't come with with NerdFont icons, so I patched it using the **Font Patcher Script** found in https://www.nerdfonts.com/.

Here's how it is rendered with PragmataPro (regular):

#### PragmataPro:
![PragmataPro](https://user-images.githubusercontent.com/3494708/192322602-a36ffee0-0775-41c2-9ce2-6658cefe6b1d.png)

#### PragmataPro Liga:
![PragmataPro Liga](https://user-images.githubusercontent.com/3494708/192322663-cfd12b0b-edf8-420f-90cf-878494873a26.png)

#### PgramataPro Mono Liga
![PragmataPro Mono Liga](https://user-images.githubusercontent.com/3494708/192322700-9ca32fe0-db78-4aa8-a9f8-c796763b9ab2.png)

I could be something to do the way you patched PragmataPro, here are the options that I've used to patch DankMono with the **Font Patcher Script**:

```bash
./FontPatcher/font-patcher DankMono-Regular.otf -l -c --careful -ext otf
```

- `-c, --complete` Add all available Glyphs
- `-l, --adjust-line-height` Whether to adjust line heights (attempt to center powerline separators more evenly)
- `--careful` Do not overwrite existing glyphs if detected
- `ext [EXTENSION], --extension [EXTENSION]` Change font file type to create (e.g., ttf, otf)

You can see all the available options in the NerdFont page at the bottom of the home page.

DankMono is showing all the available glyphs just fine. Maybe there's another option so that glyphs can be also centered horizontally. I still need to figure that out, but with those options is work perfectly already.

**Comment by vricop** [comment]
## Temporary fix for those with missing icons

I've just got it working! I've tried patching PragmataPro Liga with **NerdFont Patcher** and I've got it right in the second try with these flags (options):

```bash
./FontPatcher/font-patcher PragmataProR_liga_0829.ttf -l -c -ext otf
```

Note: there's no --careful flag, which means it'll overwrite existing glyphs

![image](https://user-images.githubusercontent.com/3494708/192451935-681b3ed5-4a02-4b51-9ba0-595f2a3b9bbb.png)

**Comment by catesandrew** [comment]
@vricop thanks but looks like we wont have to overwrite the glyphs soon with [this comment](https://github.com/ryanoasis/nerd-fonts/pull/609#issuecomment-1256009458) making reference to a [fix being available soon](https://github.com/ryanoasis/nerd-fonts/pull/773)?

**Comment by vricop** [comment]
That's good news! Thanks to let me know. In the meanwhile I'll use my patched version. @fabrizioschiavi do you notify everytime you make an update? I'm planning to buy the bold version in Christmas.

**Comment by fabrizioschiavi** [comment]
Fixed in version .830
Please re-download the font files from fsd.it
