### ISSUE TITLE
PragmataPro ligatures not rendering in terminal.app but Fira Code does

### ISSUE THREAD

**Issue by mackross** [fabrizioschiavi/pragmatapro#25]
Any idea what settings might have to change? 0.822

**Comment by fabrizioschiavi** [comment]
I know and this is a pain. 
I'll try to use `calt` instead of `liga` as OpenType feature like Fira Code but a true ligature must be supported without problem in Terminal as almost every other IDE does. 
At Apple must open their minds in these situations.
The problem will persist also with emoji and with other double-width characters

**Comment by mackross** [comment]
Damn OK. Thanks for the reply.

**Comment by freebroccolo** [comment]
FWIW, iTerm2 is apparently getting proper ligature support. See [this thread](https://gitlab.com/gnachman/iterm2/issues/3568#note_13103016).

**Comment by fabrizioschiavi** [comment]
Since version [0.824](http://www.fsd.it/shop/fonts/pragmatapro/) ligatures works also in Terminal 🎉
