### ISSUE TITLE
Full-Width Stylistic Set 'fwid' not working in VSCode.

### ISSUE THREAD

**Issue by vsr3y** [fabrizioschiavi/pragmatapro#251]
![Notepad_DVs02kthDc](https://user-images.githubusercontent.com/58370218/200226803-d4cd7438-4626-44c8-a864-d7a0e815401b.gif)
'fwid' stylistic set is not working in VSCode; other stylistic sets are tested and confirmed to work properly.
Am I missing something? Is there some CSS property that needs to be set for this to work
This seems like a language-specific issue since only Japanese use full-width variant of characters.

**Comment by fabrizioschiavi** [comment]
In my Mac it works adding
 `"editor.fontLigatures": "'fwid'" `
 in settings.json

<img width="218" alt="Screenshot 2022-11-07 at 08 44 58" src="https://user-images.githubusercontent.com/1576663/200254371-ffc3ecfc-5b8c-4b9c-989b-44316d9b7496.png">

Now I'll check also in Windows version

**Comment by fabrizioschiavi** [comment]
Also in Windows it works.

![Immagine 2022-11-07 090646](https://user-images.githubusercontent.com/1576663/200258495-fc96c167-3d7c-49c8-b03c-aeadae45f37c.png)

I can't reproduced it using PragmataPro Liga, obviously PragmataPro Mono Liga can't be used because it's monospaced and can't include double-width glyphs. Ligatures are composed by two glyphs, as explained [here](https://github.com/IBM/plex/issues/63#issuecomment-344519666), but Full Width letters are always one-width (= monospaced)
