### ISSUE TITLE
Monodraw support is not working

### ISSUE THREAD

**Issue by cdhagmann** [fabrizioschiavi/pragmatapro#264]
I have followed the instructions on the page without any luck. Is this the best place for support?

**Comment by fabrizioschiavi** [comment]
I don't know Monodraw but @phyllisstein surely yes. What didn't works exactly?

**Comment by cdhagmann** [comment]
So I apparently saved the github page instead of the .json files, which fix my initial issue. However, I cannot find any combination that allows me to recreate this:

![diagram showease](https://github.com/fabrizioschiavi/pragmatapro/assets/4440901/2ed90a69-0fd8-4b3c-839f-d2fac817ac45)

Is there a RTF or something I can reference?

**Comment by fabrizioschiavi** [comment]
[Here](https://github.com/fabrizioschiavi/pragmatapro/blob/master/showcase/PragmataPro%20Box%20Drawing%20Extra/FSD%20diagram%20sample.rtf) it is

**Comment by phyllisstein** [comment]
I confess I've stopped using Monodraw to create diagrams. I doodle on paper instead. (I still use PragmataPro everywhere else!) I can explain what's missing in the readme, though.

You have to work with Monodraw's pencil tool quite a lot. Use its box/line/text primitives, if you can, for expediency; pencil in PragmataPro characters, when necessary, for style. The GIFs in the readme give a peek at the creation and editing process. You're really building it glyph by glyph.

You'll also see a handful of rendering glitches in Monodraw. Because it assumes you're working with straight-up Menlo, it sometimes chokes on PragmataPro's more rarified code points, rendering a `?`, and doesn't bother with ligatures at all. Arrows are even sitting lower than line segments now, but only in Monodraw.

**Comment by phyllisstein** [comment]
Hilariously, you can copy and paste that RTF into Monodraw. By way of illustrating that you're better off using an RTF, the arrow line-height glitch is absent in Text Edit, absent in Monodraw's own editing box, but present in the diagram.

![CleanShot 2023-05-12 at 03 38 27](https://github.com/fabrizioschiavi/pragmatapro/assets/2207980/35945509-37a5-494b-980b-8d1caa2cc745)
