### ISSUE TITLE
PragmataPro no longer "Fixed"?

### ISSUE THREAD

**Issue by railwaycat** [fabrizioschiavi/pragmatapro#28]
I noticed that since 0.822, PragmataPro no longer listed as "Fixed" fonts under OS X FontBook, but PragmataPro Mono is; while in 0.821, both PragmataPro and PragmataPro Mono are listed as "Fixed".

**Comment by fabrizioschiavi** [comment]
This is the result of my choice: 
PragmataPro is a modular-width font now; 
PragmataPro Mono is still a fixed-width

Many glyphs are more readable at low size using a double or triple width

**Comment by railwaycat** [comment]
Thanks for the comment! I think this is quite reasonable. 

My only concern is some stupid terminal emulators only let users select monospace fonts, but anyway, such terminal emulators usually not support opentype features too, PragmataPro Mono should good enough for them.

**Comment by msva** [comment]
By the way, it is also my case (with terminals). My termnal do support glyphs, but only show Mono version of PragmataPro as acceptable choice. And since I have strange issues with Mono (terminal app experience freezes on rendering blinking text, and when rendering many text, like weechat "window"), I switched to FiraCode (which strangelly have no that issue (dunno how can it be related to font, but just fact), but do have glyphs. And that is how I checked that it pretty fine support glyphs.

So, since I liked Pragmata's look more than FiraCode, I'm now in search of fontconfig hacks (if it is ever possible) to allow selection non-mono Pragmata as monospace. But, to be honest, without any success yet :(
