### ISSUE TITLE
"Categories" not available in InDesign glyphs display

### ISSUE THREAD

**Issue by meangrape** [fabrizioschiavi/pragmatapro#280]
I don't have the right vocabulary to be precise about this so I'll do my best. In InDesign there is a glyphs display that shows all of the glyphs available in a font. It also lets you display only a subset of those glyphs. The subsets seem to be unicode ranges and OpenType features.

From Abitare Sans you can see both Cyrillic (unicode range) and Standard Ligatures (OpenType feature).
![CleanShot 2024-01-04 at 10 50 56@2x](https://github.com/fabrizioschiavi/pragmatapro/assets/9083/c4259856-6765-4e3e-ac35-4922f8e2f20b)

In PragmataPro Liga (OTF) not all of the categories are present. For instance Arabic and Hebrew are not available. Neither are Standard and Discretionary Ligatures.
![CleanShot 2024-01-04 at 10 52 24@2x](https://github.com/fabrizioschiavi/pragmatapro/assets/9083/c1e5398f-f46d-4a8c-b05e-3daf0ceb0b5e)

With a font like PragmatePro that has so many glyphs it would be useful to be able to display these smaller sets of glyphs.

I don't know how difficult this is to implement, though.

**Comment by fabrizioschiavi** [comment]
This issue is due to a limitation in @adobe, as even when using fonts like Arial Unicode, Myriad Hebrew, and Myriad Arabic, the Glyphs panel's dropdown menu does not include specific categories for Hebrew or Arabic characters.

To address this limitation, you can refer to [this link](https://helpx.adobe.com/indesign/using/glyphs-special-characters.html) for instructions on creating a custom set that includes the desired Hebrew or Arabic glyphs. Unfortunately, this is the current extent of the available workaround.
