### ISSUE TITLE
Font size increases too much between size 10 & 11 on Windows

### ISSUE THREAD

**Issue by SimWhite** [fabrizioschiavi/pragmatapro#31]
I'm really sorry but there is no any differences on latest update about #18 issue.

**Comment by fabrizioschiavi** [comment]
I verified with more attention at this case and I found the source of the problem.

A preamble:
10 pt PC = 13.33 pt Mac
11 pt PC = 14.67 pt Mac
14 pt Mac = 10.5 pt PC

After the scaling of all the glyphs, unfortunately the heights fallen in a alignment point that does not allow it to be changed without altering the real one

To increase the height of 10pt I must add 1 pixel to the top of the glyphs at 13pt Mac
Please see by yourself if is possible seeing the following screenshot
![13mac](https://cloud.githubusercontent.com/assets/1576663/18555538/87522486-7b68-11e6-8203-b4719669c984.png)
We are already above the line-height of the grid

I suggest you to set up PragmataPro using **10.5** to obtain the right scaling effect and to taking advantage of the perfect hinting of 14 pt Mac

**Comment by rnetocombr** [comment]
Fabrizio,

This has a big impact for Windows users. 

In some softwares for Windows the only possible font sizes are multiples of two (10, 12, 14). Others applications use integers (10, 11, 12, 13), so you can´t simply set 10.5.  When the user sets Pragmata for these sizes the hinting is severely compromissed.

Maybe an alternative fix could be thought ?

Thanks for your work. Peace!

**Comment by rnetocombr** [comment]
@fabrizioschiavi 

First, Happy new year! Wish a great 2017 for you, professionally and personally.

I love PragmataPro but this bug is really annoying for Windows users. 

Check the screenshots attached.

Most of Windows software does not accept floats font sizes. 

Previous versions of PragmataPro rendered great at sizes like 12px and 13px.

There is some change we can make to fit the perfect hinting to the integer sizes in Windows ? Increase line height or something like that. For me, it’s a greate tradeoff, as hinting plays a major importance for me.

Cheers!

![pragmatapro_0821](https://cloud.githubusercontent.com/assets/1286199/21547306/f50f46f4-cdc3-11e6-834d-2e38b78391e5.PNG)
![pragmatapro_0824](https://cloud.githubusercontent.com/assets/1286199/21547307/f55d8904-cdc3-11e6-92c1-c8eb9c988595.PNG)

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
